version: '3.8'

services:
  # MongoDB database
  mongo:
    image: mongo:7.0
    container_name: civicpulse-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: civicpulse
    volumes:
      - mongo_data:/data/db
    networks:
      - civicpulse-network

  # Backend API server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: civicpulse-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password123@mongo:27017/civicpulse?authSource=admin
      - JWT_SECRET=your-jwt-secret-here-change-in-production
      - GUEST_PASSWORD=guest123
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - civicpulse-network

  # Frontend Next.js application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: civicpulse-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - civicpulse-network

volumes:
  mongo_data:
    driver: local

networks:
  civicpulse-network:
    driver: bridge