version: '3.8'

services:
  # MongoDB database
  mongo:
    image: mongo:7.0
    container_name: civicsense-mongo-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: civicsense
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - civicsense-network

  # Backend API server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: civicsense-backend-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password123@mongo:27017/civicsense?authSource=admin
      - JWT_SECRET=development-jwt-secret-change-in-production
      - GUEST_PASSWORD=guest123
    volumes:
      - ./scripts:/app/scripts
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - civicsense-network
    command: npm run start:dev

  # Frontend Next.js application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: civicsense-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3001
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - civicsense-network
    command: npm run dev

volumes:
  mongo_data_dev:
    driver: local

networks:
  civicsense-network:
    driver: bridge